### ISSUE TITLE
Unable to use

### ISSUE THREAD

**Issue by RichardLitt** [JohnByrneRepo/mddir#7]
Hey! Thanks for this module. I tried to use it today, and found this error:

```sh
$ mddir
env: node\r: No such file or directory
```

Not sure what is up, here.

**Comment by marcobarbosa** [comment]
Same issue here. I believe this for Mac users? Seems like it has to do with line endings.

EDIT: [This comment](https://github.com/tonistiigi/audiosprite/issues/51#issuecomment-252398978) has a good fix suggestion. Worked for me.

**Comment by RichardLitt** [comment]
I was unable to find any `\r` chars using a regex in my cloned copy. :/

**Comment by SargoDarya** [comment]
@RichardLitt \r is a newline character. Fix is in develop and should be published soon.

**Comment by JohnByrneRepo** [comment]
Hi, thanks for trying out my library. Apologies for the delay. I've found a fix for this, and updated the readme. It's possible I merged a pr on a Windows system and I am looking into a longer term solution. For now though:

Line endings fix

Get npm bin folder path with:

npm config get prefix

Cd into that folder

brew install dos2unix

dos2unix lib/node_modules/mddir/src/mddir.js

This converts line endings to Unix instead of Dos

Then run as normal with: node mddir "../relative/path/"

**Comment by ispyhumanfly** [comment]
I have resolved this in my latest pull request by making another mddir command called mddir-nix which works on all Unix flavors. See some of the updates I made here #10 . You can also view my version at http://github.com/flypapertech/mddir

**Comment by RichardLitt** [comment]
I can no longer replicate. As I opened this, I'm going to close it. Thank you, @JohnByrneRepo.
